name: Platformer Generated test-workflow Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: fdfg/jgj
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag
          ${SERVICE_NAME}:${{steps.branch_name.outputs.SOURCE_TAG }}
      - name: Docker Push
        run: docker push $SERVICE_NAME:$TAG
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_8e72a7ad-a394-42e3-be56-5c5e3463a0e4}}
          project-id: ${{secrets.PROJECT_ID_8e72a7ad-a394-42e3-be56-5c5e3463a0e4}}
          token: ${{secrets.AUTOGENERATED_CICD_8e72a7ad-a394-42e3-be56-5c5e3463a0e4}}
          image-name: $SERVICE_NAME
          tag: ${{steps.branch_name.outputs.SOURCE_TAG }}
          container-id: b8a6cc25-1bc2-42d7-ae52-a724a623f66d
